# Prefix
unbind C-a
set -g prefix C-\\
bind C-\\ send-prefix

# Faster escape
set -sg escape-time 10

# Mouse (useful for resize)
set -g mouse on

# Pane splitting
bind | split-window -h
bind - split-window -v

# Vim-like navigation
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Resize panes
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

# Start index at 1
set -g base-index 1
setw -g pane-base-index 1

# Better colors
set -g default-terminal "tmux-256color"

# Reload config
bind r source-file ~/.tmux.conf \; display "Reloaded!"
